[package]
edition = "2018"
name = "wgpu-renderer"
version = "0.1.0"

[dependencies]
anyhow = "1.0.43"
cgmath = "0.18"
env_logger = "0.9"
image = "0.23"
log = "0.4"
pollster = "0.2"
wgpu = "0.9"
winit = "0.25"

[dependencies.bytemuck]
features = ["derive"]
version = "1.4"
